### ISSUE TITLE
No property title on Gjs_ui_quickSettings_QuickMenuToggle

### ISSUE THREAD

**Issue by jrgn9** [AzzamAlsharafi/ideapad-controls-gnome-extension#10]
Error with the message "No property title on Gjs_ui_quickSettings_QuickMenuToggle" makes the extension unusable. I am running GNOME 43.4

**Comment by AzzamAlsharafi** [comment]
I pushed a fix, can you test it on your machine? Clone the repo and use the `install.sh` script to install the extension manually.

**Comment by jrgn9** [comment]
That did the trick! Thank you very much
