### ISSUE TITLE
Enable switch between 'Tray' and 'System Menu' without an extension reload

### ISSUE THREAD

**Issue by CorvetteCole** [AzzamAlsharafi/ideapad-controls-gnome-extension#2]
This can be done quite easily by attaching a listener for that settings change in the enable() function, just make sure to detach it in disable().

I may implement this myself at some point if I have time and if desired by the maintainer

**Comment by AzzamAlsharafi** [comment]
I wasn't aware that you can connect a listener to the settings, I thought you could only do "bind" which is limited. Thanks for the tip, I'll implement it now.

**Comment by CorvetteCole** [comment]
maybe I misspoke and meant binding, you can see how blur-my-shell does it here: https://github.com/aunetx/blur-my-shell/blob/master/src/extension.js

**Comment by AzzamAlsharafi** [comment]
Yeah I get what you mean. I already did it using settings.connect().
