### ISSUE TITLE
What "USB charging" means?

### ISSUE THREAD

**Issue by ghost** [AzzamAlsharafi/ideapad-controls-gnome-extension#6]
What "USB charging" means? Is it the same as the "rapid charge"?

btw thank you for this extension :)

**Comment by AzzamAlsharafi** [comment]
USB charging is the ability of the laptop to charge devices connected to it while it's powered off. 

So when USB charging is enabled you will be able to charge a phone by connecting it to the laptop, even if the laptop is shutdown.

**Comment by ghost** [comment]
thanks for the explanation
