### ISSUE TITLE
Requiring password on every action toggle

### ISSUE THREAD

**Issue by SageTendo** [AzzamAlsharafi/ideapad-controls-gnome-extension#7]
Is there a way of giving the extension sudo access automatically?

**Comment by AzzamAlsharafi** [comment]
Unfortunately, I couldn't find a way to achieve that.

**Comment by paulo-roger** [comment]
Maybe giving it sudo auth like we do with docker?

**Comment by AzzamAlsharafi** [comment]
Feature has been added in PR #12 by @Woomymy. Update to the latest release and follow the instructions in README.
