### ISSUE TITLE
Menu label missing with Gnome 44

### ISSUE THREAD

**Issue by cleveHEX** [AzzamAlsharafi/ideapad-controls-gnome-extension#8]
![obrazek](https://user-images.githubusercontent.com/9021297/231565599-d2212ee8-e832-4c5a-96de-4039fc1191d7.png)

**Comment by AlexMicael** [comment]
Changing "label" to "title" on quickSettingsMenu.js fixes this.

**Comment by AzzamAlsharafi** [comment]
Fixed in the repository. Wait until the update is approved in gnome-extensions website, or you can install directly using `install.sh`.
