### ISSUE TITLE
Quick setting is beneath background apps button GNOME 44

### ISSUE THREAD

**Issue by TheAgamer554** [AzzamAlsharafi/ideapad-controls-gnome-extension#9]
![Captura desde 2023-04-26 17-40-49](https://user-images.githubusercontent.com/42060301/234629177-48a5f29d-30fd-4fb4-8169-7e39563a33a3.png)

**Comment by AzzamAlsharafi** [comment]
Thanks for raising issue. It has been fixed in the latest commit. You can wait for the update to be approved on gnome-extensions website, or install manually using `install.sh`.
